A = Hexagon(0, 0, 100)
B = A.cube()
E = Cube(Coordinate(B.loc.x - 0.353, B.loc.y - 0.353, B.loc.z), 100)
C = Cube(Coordinate(E.loc.x, E.loc.y + 1, E.loc.z), 100)
D = Cube(Coordinate(E.loc.x + 1, E.loc.y, E.loc.z), 100)
C.hexagon().draw()
D.hexagon().draw()
E.hexagon().draw()
A.draw()
